# SPDX-FileCopyrightText: 2025-2026 Vacuumlabs
# SPDX-License-Identifier: Apache-2.0

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
UNIT_TESTS_DIR = REPO_ROOT / "unit-tests"
FIXTURES_DIR = UNIT_TESTS_DIR

GENERATED_DIR = UNIT_TESTS_DIR / "generated"
GENERATED_SIGN_TX_DIR = GENERATED_DIR / "sign_tx"
GENERATED_SIGN_MSG_DIR = GENERATED_DIR / "sign_msg"
GENERATED_PUBKEY_DIR = GENERATED_DIR / "pubkey"
GENERATED_DERIVE_ADDRESS_DIR = GENERATED_DIR / "derive_address"
GENERATED_NATIVE_SCRIPT_DIR = GENERATED_DIR / "native_script"
GENERATED_CVOTE_DIR = GENERATED_DIR / "cvote"
GENERATED_OPCERT_DIR = GENERATED_DIR / "opcert"
