// SPDX-FileCopyrightText: 2025-2026 Vacuumlabs
// SPDX-License-Identifier: Apache-2.0

// Generated by: unit-tests/generators/generate_unit_tests_from_ragger.py

// Unit tests for transaction signing (auto-generated)
// DO NOT EDIT - regenerate using generators/generate_unit_tests_from_ragger.py

#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#include <cmocka.h>

#include "apdu/dispatcher.h"
#include "handler/sign_tx.h"
#include "buffer.h"
#include "cardano_swo.h"
#include "cardano_constants.h"
#include "globals.h"
#include "tx.h"
#include "tx_parse.h"
#include "securityPolicy/securityPolicy.h"
#include "hexUtils.h"
#include "utils/utils.h"
#include "blake2b.h"
#include "init_apdu.h"
#include "io_capture.h"

#include "test_sign_tx_fixtures_alonzo_cip36.h"

#include "test_sign_tx_common.h"
#include "app_mem_utils.h"

// ======================================================================
// UI code: using REAL ui_display_*.c with mocked NBGL
// ======================================================================
// The real UI code from ../src/ui/ui_display_tx.c and ui_display_witness.c
// is included in cardano_sign_tx_core library. It calls NBGL functions which
// are mocked in mock_sources/nbgl_mock.c to auto-approve for testing.
// This way we test the actual UI formatting, tag-value pair generation,
// and state management logic.

// ======================================================================
// ALONZO_CIP36 Era Tests
// ======================================================================

static void test_sign_tx_with_cip36_registration_with_vote_key_hex_expert_off(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTE_KEY_HEX, false);
}

static void test_sign_tx_with_cip36_registration_with_vote_key_hex_reject_tx_expert_off(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTE_KEY_HEX, false);
}

static void test_sign_tx_with_cip36_registration_with_vote_key_hex_reject_aux_expert_off(void **state) {
    (void) state;
    run_fixture_reject_aux_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTE_KEY_HEX, false);
}

static void test_sign_tx_with_cip36_registration_with_vote_key_hex_expert_on(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTE_KEY_HEX, true);
}

static void test_sign_tx_with_cip36_registration_with_vote_key_hex_reject_tx_expert_on(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTE_KEY_HEX, true);
}

static void test_sign_tx_with_cip36_registration_with_vote_key_hex_reject_aux_expert_on(void **state) {
    (void) state;
    run_fixture_reject_aux_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTE_KEY_HEX, true);
}

static void test_sign_tx_with_cip36_registration_with_vote_key_path_expert_off(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTE_KEY_PATH, false);
}

static void test_sign_tx_with_cip36_registration_with_vote_key_path_reject_tx_expert_off(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTE_KEY_PATH, false);
}

static void test_sign_tx_with_cip36_registration_with_vote_key_path_reject_aux_expert_off(void **state) {
    (void) state;
    run_fixture_reject_aux_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTE_KEY_PATH, false);
}

static void test_sign_tx_with_cip36_registration_with_vote_key_path_expert_on(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTE_KEY_PATH, true);
}

static void test_sign_tx_with_cip36_registration_with_vote_key_path_reject_tx_expert_on(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTE_KEY_PATH, true);
}

static void test_sign_tx_with_cip36_registration_with_vote_key_path_reject_aux_expert_on(void **state) {
    (void) state;
    run_fixture_reject_aux_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTE_KEY_PATH, true);
}

static void test_sign_tx_with_cip36_registration_with_unusual_vote_key_path_expert_off(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_UNUSUAL_VOTE_KEY_PATH, false);
}

static void test_sign_tx_with_cip36_registration_with_unusual_vote_key_path_reject_tx_expert_off(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_UNUSUAL_VOTE_KEY_PATH, false);
}

static void test_sign_tx_with_cip36_registration_with_unusual_vote_key_path_reject_aux_expert_off(void **state) {
    (void) state;
    run_fixture_reject_aux_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_UNUSUAL_VOTE_KEY_PATH, false);
}

static void test_sign_tx_with_cip36_registration_with_unusual_vote_key_path_expert_on(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_UNUSUAL_VOTE_KEY_PATH, true);
}

static void test_sign_tx_with_cip36_registration_with_unusual_vote_key_path_reject_tx_expert_on(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_UNUSUAL_VOTE_KEY_PATH, true);
}

static void test_sign_tx_with_cip36_registration_with_unusual_vote_key_path_reject_aux_expert_on(void **state) {
    (void) state;
    run_fixture_reject_aux_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_UNUSUAL_VOTE_KEY_PATH, true);
}

static void test_sign_tx_with_cip36_registration_with_thirdparty_payment_address_expert_off(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_THIRDPARTY_PAYMENT_ADDRESS, false);
}

static void test_sign_tx_with_cip36_registration_with_thirdparty_payment_address_reject_tx_expert_off(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_THIRDPARTY_PAYMENT_ADDRESS, false);
}

static void test_sign_tx_with_cip36_registration_with_thirdparty_payment_address_reject_aux_expert_off(void **state) {
    (void) state;
    run_fixture_reject_aux_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_THIRDPARTY_PAYMENT_ADDRESS, false);
}

static void test_sign_tx_with_cip36_registration_with_thirdparty_payment_address_expert_on(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_THIRDPARTY_PAYMENT_ADDRESS, true);
}

static void test_sign_tx_with_cip36_registration_with_thirdparty_payment_address_reject_tx_expert_on(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_THIRDPARTY_PAYMENT_ADDRESS, true);
}

static void test_sign_tx_with_cip36_registration_with_thirdparty_payment_address_reject_aux_expert_on(void **state) {
    (void) state;
    run_fixture_reject_aux_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_THIRDPARTY_PAYMENT_ADDRESS, true);
}

static void test_sign_tx_with_cip36_registration_with_voting_purpose_expert_off(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTING_PURPOSE, false);
}

static void test_sign_tx_with_cip36_registration_with_voting_purpose_reject_tx_expert_off(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTING_PURPOSE, false);
}

static void test_sign_tx_with_cip36_registration_with_voting_purpose_reject_aux_expert_off(void **state) {
    (void) state;
    run_fixture_reject_aux_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTING_PURPOSE, false);
}

static void test_sign_tx_with_cip36_registration_with_voting_purpose_expert_on(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTING_PURPOSE, true);
}

static void test_sign_tx_with_cip36_registration_with_voting_purpose_reject_tx_expert_on(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTING_PURPOSE, true);
}

static void test_sign_tx_with_cip36_registration_with_voting_purpose_reject_aux_expert_on(void **state) {
    (void) state;
    run_fixture_reject_aux_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_VOTING_PURPOSE, true);
}

static void test_sign_tx_with_cip36_registration_with_delegations_expert_off(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_DELEGATIONS, false);
}

static void test_sign_tx_with_cip36_registration_with_delegations_reject_tx_expert_off(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_DELEGATIONS, false);
}

static void test_sign_tx_with_cip36_registration_with_delegations_reject_aux_expert_off(void **state) {
    (void) state;
    run_fixture_reject_aux_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_DELEGATIONS, false);
}

static void test_sign_tx_with_cip36_registration_with_delegations_expert_on(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_DELEGATIONS, true);
}

static void test_sign_tx_with_cip36_registration_with_delegations_reject_tx_expert_on(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_DELEGATIONS, true);
}

static void test_sign_tx_with_cip36_registration_with_delegations_reject_aux_expert_on(void **state) {
    (void) state;
    run_fixture_reject_aux_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_DELEGATIONS, true);
}

static void test_sign_tx_with_cip36_registration_with_many_delegations_streaming_expert_off(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_MANY_DELEGATIONS_STREAMING, false);
}

static void test_sign_tx_with_cip36_registration_with_many_delegations_streaming_reject_tx_expert_off(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_MANY_DELEGATIONS_STREAMING, false);
}

static void test_sign_tx_with_cip36_registration_with_many_delegations_streaming_reject_aux_expert_off(void **state) {
    (void) state;
    run_fixture_reject_aux_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_MANY_DELEGATIONS_STREAMING, false);
}

static void test_sign_tx_with_cip36_registration_with_many_delegations_streaming_expert_on(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_MANY_DELEGATIONS_STREAMING, true);
}

static void test_sign_tx_with_cip36_registration_with_many_delegations_streaming_reject_tx_expert_on(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_MANY_DELEGATIONS_STREAMING, true);
}

static void test_sign_tx_with_cip36_registration_with_many_delegations_streaming_reject_aux_expert_on(void **state) {
    (void) state;
    run_fixture_reject_aux_with_expert_mode(&FIXTURE_ALONZO_CIP36_SIGN_TX_WITH_CIP36_REGISTRATION_WITH_MANY_DELEGATIONS_STREAMING, true);
}

// ======================================================================
// Main
// ======================================================================

int main(void) {
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_vote_key_hex_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_vote_key_hex_reject_tx_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_vote_key_hex_reject_aux_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_vote_key_hex_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_vote_key_hex_reject_tx_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_vote_key_hex_reject_aux_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_vote_key_path_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_vote_key_path_reject_tx_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_vote_key_path_reject_aux_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_vote_key_path_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_vote_key_path_reject_tx_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_vote_key_path_reject_aux_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_unusual_vote_key_path_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_unusual_vote_key_path_reject_tx_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_unusual_vote_key_path_reject_aux_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_unusual_vote_key_path_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_unusual_vote_key_path_reject_tx_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_unusual_vote_key_path_reject_aux_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_thirdparty_payment_address_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_thirdparty_payment_address_reject_tx_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_thirdparty_payment_address_reject_aux_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_thirdparty_payment_address_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_thirdparty_payment_address_reject_tx_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_thirdparty_payment_address_reject_aux_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_voting_purpose_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_voting_purpose_reject_tx_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_voting_purpose_reject_aux_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_voting_purpose_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_voting_purpose_reject_tx_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_voting_purpose_reject_aux_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_delegations_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_delegations_reject_tx_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_delegations_reject_aux_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_delegations_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_delegations_reject_tx_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_delegations_reject_aux_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_many_delegations_streaming_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_many_delegations_streaming_reject_tx_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_many_delegations_streaming_reject_aux_expert_off),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_many_delegations_streaming_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_many_delegations_streaming_reject_tx_expert_on),
        cmocka_unit_test(test_sign_tx_with_cip36_registration_with_many_delegations_streaming_reject_aux_expert_on),
    };
    return _cmocka_run_group_tests("test_sign_tx_alonzo_cip36", tests, ARRAY_LEN(tests), NULL, NULL);
}
