// SPDX-FileCopyrightText: 2025-2026 Vacuumlabs
// SPDX-License-Identifier: Apache-2.0

// Generated by: unit-tests/generators/generate_unit_tests_from_ragger.py

// Unit tests for transaction signing (auto-generated)
// DO NOT EDIT - regenerate using generators/generate_unit_tests_from_ragger.py

#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

#include <cmocka.h>

#include "apdu/dispatcher.h"
#include "handler/sign_tx.h"
#include "buffer.h"
#include "cardano_swo.h"
#include "cardano_constants.h"
#include "globals.h"
#include "tx.h"
#include "tx_parse.h"
#include "securityPolicy/securityPolicy.h"
#include "hexUtils.h"
#include "utils/utils.h"
#include "blake2b.h"
#include "init_apdu.h"
#include "io_capture.h"

#include "test_sign_tx_fixtures_mary.h"

#include "test_sign_tx_common.h"
#include "app_mem_utils.h"

// ======================================================================
// UI code: using REAL ui_display_*.c with mocked NBGL
// ======================================================================
// The real UI code from ../src/ui/ui_display_tx.c and ui_display_witness.c
// is included in cardano_sign_tx_core library. It calls NBGL functions which
// are mocked in mock_sources/nbgl_mock.c to auto-approve for testing.
// This way we test the actual UI formatting, tag-value pair generation,
// and state management logic.

// ======================================================================
// MARY Era Tests
// ======================================================================

static void test_sign_tx_with_a_multiasset_output_expert_off(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_A_MULTIASSET_OUTPUT, false);
}

static void test_sign_tx_with_a_multiasset_output_reject_tx_expert_off(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_A_MULTIASSET_OUTPUT, false);
}

static void test_sign_tx_with_a_multiasset_output_expert_on(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_A_MULTIASSET_OUTPUT, true);
}

static void test_sign_tx_with_a_multiasset_output_reject_tx_expert_on(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_A_MULTIASSET_OUTPUT, true);
}

static void test_sign_tx_with_a_complex_multiasset_output_expert_off(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_A_COMPLEX_MULTIASSET_OUTPUT, false);
}

static void test_sign_tx_with_a_complex_multiasset_output_reject_tx_expert_off(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_A_COMPLEX_MULTIASSET_OUTPUT, false);
}

static void test_sign_tx_with_a_complex_multiasset_output_expert_on(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_A_COMPLEX_MULTIASSET_OUTPUT, true);
}

static void test_sign_tx_with_a_complex_multiasset_output_reject_tx_expert_on(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_A_COMPLEX_MULTIASSET_OUTPUT, true);
}

static void test_sign_tx_with_big_numbers_expert_off(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_BIG_NUMBERS, false);
}

static void test_sign_tx_with_big_numbers_reject_tx_expert_off(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_BIG_NUMBERS, false);
}

static void test_sign_tx_with_big_numbers_expert_on(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_BIG_NUMBERS, true);
}

static void test_sign_tx_with_big_numbers_reject_tx_expert_on(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_BIG_NUMBERS, true);
}

static void test_sign_tx_with_a_multiasset_change_output_expert_off(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_A_MULTIASSET_CHANGE_OUTPUT, false);
}

static void test_sign_tx_with_a_multiasset_change_output_reject_tx_expert_off(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_A_MULTIASSET_CHANGE_OUTPUT, false);
}

static void test_sign_tx_with_a_multiasset_change_output_expert_on(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_A_MULTIASSET_CHANGE_OUTPUT, true);
}

static void test_sign_tx_with_a_multiasset_change_output_reject_tx_expert_on(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_A_MULTIASSET_CHANGE_OUTPUT, true);
}

static void test_sign_tx_with_zero_fee_ttl_and_validity_interval_start_expert_off(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_ZERO_FEE_TTL_AND_VALIDITY_INTERVAL_START, false);
}

static void test_sign_tx_with_zero_fee_ttl_and_validity_interval_start_reject_tx_expert_off(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_ZERO_FEE_TTL_AND_VALIDITY_INTERVAL_START, false);
}

static void test_sign_tx_with_zero_fee_ttl_and_validity_interval_start_expert_on(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_ZERO_FEE_TTL_AND_VALIDITY_INTERVAL_START, true);
}

static void test_sign_tx_with_zero_fee_ttl_and_validity_interval_start_reject_tx_expert_on(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_ZERO_FEE_TTL_AND_VALIDITY_INTERVAL_START, true);
}

static void test_sign_tx_with_output_with_decimal_places_expert_off(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_OUTPUT_WITH_DECIMAL_PLACES, false);
}

static void test_sign_tx_with_output_with_decimal_places_reject_tx_expert_off(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_OUTPUT_WITH_DECIMAL_PLACES, false);
}

static void test_sign_tx_with_output_with_decimal_places_expert_on(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_OUTPUT_WITH_DECIMAL_PLACES, true);
}

static void test_sign_tx_with_output_with_decimal_places_reject_tx_expert_on(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_OUTPUT_WITH_DECIMAL_PLACES, true);
}

static void test_sign_tx_with_mint_fields_with_various_amounts_expert_off(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_MINT_FIELDS_WITH_VARIOUS_AMOUNTS, false);
}

static void test_sign_tx_with_mint_fields_with_various_amounts_reject_tx_expert_off(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_MINT_FIELDS_WITH_VARIOUS_AMOUNTS, false);
}

static void test_sign_tx_with_mint_fields_with_various_amounts_expert_on(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_MINT_FIELDS_WITH_VARIOUS_AMOUNTS, true);
}

static void test_sign_tx_with_mint_fields_with_various_amounts_reject_tx_expert_on(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_MINT_FIELDS_WITH_VARIOUS_AMOUNTS, true);
}

static void test_sign_tx_with_mint_with_decimal_places_expert_off(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_MINT_WITH_DECIMAL_PLACES, false);
}

static void test_sign_tx_with_mint_with_decimal_places_reject_tx_expert_off(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_MINT_WITH_DECIMAL_PLACES, false);
}

static void test_sign_tx_with_mint_with_decimal_places_expert_on(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_MINT_WITH_DECIMAL_PLACES, true);
}

static void test_sign_tx_with_mint_with_decimal_places_reject_tx_expert_on(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_MINT_WITH_DECIMAL_PLACES, true);
}

static void test_sign_tx_with_mint_fields_among_other_fields_expert_off(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_MINT_FIELDS_AMONG_OTHER_FIELDS, false);
}

static void test_sign_tx_with_mint_fields_among_other_fields_reject_tx_expert_off(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_MINT_FIELDS_AMONG_OTHER_FIELDS, false);
}

static void test_sign_tx_with_mint_fields_among_other_fields_expert_on(void **state) {
    (void) state;
    run_fixture_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_MINT_FIELDS_AMONG_OTHER_FIELDS, true);
}

static void test_sign_tx_with_mint_fields_among_other_fields_reject_tx_expert_on(void **state) {
    (void) state;
    run_fixture_reject_tx_with_expert_mode(&FIXTURE_MARY_SIGN_TX_WITH_MINT_FIELDS_AMONG_OTHER_FIELDS, true);
}

// ======================================================================
// Main
// ======================================================================

int main(void) {
    const struct CMUnitTest tests[] = {
        cmocka_unit_test(test_sign_tx_with_a_multiasset_output_expert_off),
        cmocka_unit_test(test_sign_tx_with_a_multiasset_output_reject_tx_expert_off),
        cmocka_unit_test(test_sign_tx_with_a_multiasset_output_expert_on),
        cmocka_unit_test(test_sign_tx_with_a_multiasset_output_reject_tx_expert_on),
        cmocka_unit_test(test_sign_tx_with_a_complex_multiasset_output_expert_off),
        cmocka_unit_test(test_sign_tx_with_a_complex_multiasset_output_reject_tx_expert_off),
        cmocka_unit_test(test_sign_tx_with_a_complex_multiasset_output_expert_on),
        cmocka_unit_test(test_sign_tx_with_a_complex_multiasset_output_reject_tx_expert_on),
        cmocka_unit_test(test_sign_tx_with_big_numbers_expert_off),
        cmocka_unit_test(test_sign_tx_with_big_numbers_reject_tx_expert_off),
        cmocka_unit_test(test_sign_tx_with_big_numbers_expert_on),
        cmocka_unit_test(test_sign_tx_with_big_numbers_reject_tx_expert_on),
        cmocka_unit_test(test_sign_tx_with_a_multiasset_change_output_expert_off),
        cmocka_unit_test(test_sign_tx_with_a_multiasset_change_output_reject_tx_expert_off),
        cmocka_unit_test(test_sign_tx_with_a_multiasset_change_output_expert_on),
        cmocka_unit_test(test_sign_tx_with_a_multiasset_change_output_reject_tx_expert_on),
        cmocka_unit_test(test_sign_tx_with_zero_fee_ttl_and_validity_interval_start_expert_off),
        cmocka_unit_test(test_sign_tx_with_zero_fee_ttl_and_validity_interval_start_reject_tx_expert_off),
        cmocka_unit_test(test_sign_tx_with_zero_fee_ttl_and_validity_interval_start_expert_on),
        cmocka_unit_test(test_sign_tx_with_zero_fee_ttl_and_validity_interval_start_reject_tx_expert_on),
        cmocka_unit_test(test_sign_tx_with_output_with_decimal_places_expert_off),
        cmocka_unit_test(test_sign_tx_with_output_with_decimal_places_reject_tx_expert_off),
        cmocka_unit_test(test_sign_tx_with_output_with_decimal_places_expert_on),
        cmocka_unit_test(test_sign_tx_with_output_with_decimal_places_reject_tx_expert_on),
        cmocka_unit_test(test_sign_tx_with_mint_fields_with_various_amounts_expert_off),
        cmocka_unit_test(test_sign_tx_with_mint_fields_with_various_amounts_reject_tx_expert_off),
        cmocka_unit_test(test_sign_tx_with_mint_fields_with_various_amounts_expert_on),
        cmocka_unit_test(test_sign_tx_with_mint_fields_with_various_amounts_reject_tx_expert_on),
        cmocka_unit_test(test_sign_tx_with_mint_with_decimal_places_expert_off),
        cmocka_unit_test(test_sign_tx_with_mint_with_decimal_places_reject_tx_expert_off),
        cmocka_unit_test(test_sign_tx_with_mint_with_decimal_places_expert_on),
        cmocka_unit_test(test_sign_tx_with_mint_with_decimal_places_reject_tx_expert_on),
        cmocka_unit_test(test_sign_tx_with_mint_fields_among_other_fields_expert_off),
        cmocka_unit_test(test_sign_tx_with_mint_fields_among_other_fields_reject_tx_expert_off),
        cmocka_unit_test(test_sign_tx_with_mint_fields_among_other_fields_expert_on),
        cmocka_unit_test(test_sign_tx_with_mint_fields_among_other_fields_reject_tx_expert_on),
    };
    return _cmocka_run_group_tests("test_sign_tx_mary", tests, ARRAY_LEN(tests), NULL, NULL);
}
